language: cpp
sudo: false
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    - llvm-toolchain-precise-3.8
    - george-edison55-precise-backports
    packages:
    - g++-5
    - clang-3.8
    - cmake
    - cmake-data
matrix:
    include:
        - name: Linux (gcc-5)
          os: linux
          compiler: gcc
        - name: Linux (clang)
          os: linux
          compiler: clang
before_install:
  - $CC --version
  - cmake --version
before_script:
  - cmake .
script:
  - make
  - make test
